### ISSUE TITLE
Errors when use ifile and material command only to define the material model

### ISSUE THREAD

**Issue by eamonustc** [geodynamics/sw4#10] opened 2017-05-01 09:18 UTC
Hi:
        I try to use ifile and material command only to define my material model. I always got these errors:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
MaterialIfile:: set_material_properties: Total # points=729552795. Defined properties in # points=729517344
setMaterials> mMaterialExtrapolate = 0, mNumberOfCartesianGrids=1

       ----------- Material properties ranges ---------------
       -1.00000000e+00 kg/m^3 <=  Density <= 3.20000000e+03 kg/m^3
       1.00000000e+00 m/s    <=  Vp      <= 8.00000000e+03 m/s
       1.00000000e+00 m/s    <=  Vs      <= 4.70000000e+03 m/s
       1.00000000e+00        <=  Vp/Vs   <= 4.85714286e+00
       -1.00000000e+00 Pa     <=  mu      <= 7.06880000e+10 Pa
       1.00000000e+00 Pa     <=  lambda  <= 6.34240000e+10 Pa
       ------------------------------------------------------
Verification failed: Error: vp/vs is smaller than sqrt(2).
...at line 139 of file ../src/material.C.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

But when I use block command (block vp=1700 vs=350 rho=1800) before ifile and material command, there is no error. And the computation domain is inside my ifile.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Geographic and Cartesian coordinates of the corners of the computational grid:
0: Lon= 1.294500e+02, Lat=3.090000e+01, x=0.000000e+00, y=0.000000e+00
1: Lon= 1.294500e+02, Lat=3.404410e+01, x=3.500000e+05, y=0.000000e+00
2: Lon= 1.321603e+02, Lat=3.404410e+01, x=3.500000e+05, y=2.500000e+05
3: Lon= 1.320673e+02, Lat=3.090000e+01, x=0.000000e+00, y=2.500000e+05

**** Ifile parameters: *****
filename=jiv.dat
CartesianFormat=0
***inside MaterialIfile::extractSurfaceFromGridFile***
Nlon=233 Nlat=403 Nmat=23
Material interface surfaces: lonMin=1.293500e+02, lonMax=1.322500e+02
latMin=3.080000e+01, latMax=3.415000e+01
depthMin=0.000000e+00, depthMax=6.291780e+05
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I do not know the reason.

**Comment by shaharkadmiel** [comment] 2017-05-01 12:33
Please show your input file or at least the ``ifile`` and ``material`` lines.

Note that your ``Material properties ranges`` are non-physical. Specifically, Vp_min cannot equal Vs_min. The setup routine of SW4 checks that ``Vp/Vs >= sqrt(2)``. I am not sure but I am also almost positive that you cannot have negative values in your domain. Note ``rho_min`` and ``mu_min``

**Comment by eamonustc** [comment] 2017-05-01 13:42
My input file:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fileio path=kumamoto verbose=3

# grid size is set in the grid command
grid x=350e3 y=250e3 z=60e3 lat=30.90 lon=129.45 h=200.0

time t=300.0

# source model
source lon=130.8495 lat=32.7755 depth=8000.0 strike=283 dip=58 rake=-30 m0=1.429e+17 t0=0.0 freq=1.0 type=Triangle

# 1D velocity model
# block vp=1700 vs=350 rho=1800

# material model
material id=1 vp=1700 vs=350 rho=1800
material id=2 vp=1800 vs=500 rho=1950
material id=3 vp=2000 vs=600 rho=2000
material id=4 vp=2100 vs=700 rho=2050
material id=5 vp=2200 vs=800 rho=2070
material id=6 vp=2300 vs=900 rho=2100
material id=7 vp=2400 vs=1000 rho=2150
material id=8 vp=2700 vs=1300 rho=2200
material id=9 vp=3000 vs=1500 rho=2250
material id=10 vp=3200 vs=1700 rho=2300
material id=11 vp=3500 vs=2000 rho=2350
material id=12 vp=4200 vs=2400 rho=2450
material id=13 vp=5000 vs=2900 rho=2600
material id=14 vp=5500 vs=3200 rho=2650
material id=15 vp=5800 vs=3400 rho=2700
material id=16 vp=6400 vs=3800 rho=2800
material id=17 vp=7500 vs=4500 rho=3200
material id=18 vp=5000 vs=2900 rho=2400
material id=19 vp=6800 vs=4000 rho=2900
material id=20 vp=8000 vs=4700 rho=3200
material id=21 vp=5400 vs=2800 rho=2600
material id=22 vp=6500 vs=3500 rho=2800
material id=23 vp=8100 vs=4600 rho=3400

# velocity model
ifile filename=kumamoto.dat input=geographic

# global threshold on material velocities
# globalmaterial vpmin=1700 vsmin=350

# images
image mode=s x=150.0 cycle=0 precision=double file=jvmod

# only use broadband stations
rec lon=131.3062 lat=33.4701 depth=0.0 sta=INN file=INN nsew=1 usgsformat=0 sacformat=1
rec lon=130.2530 lat=33.5052 depth=0.0 sta=SBR file=SBR nsew=1 usgsformat=0 sacformat=1
rec lon=130.3486 lat=31.9698 depth=0.0 sta=SIB file=SIB nsew=1 usgsformat=0 sacformat=1
rec lon=130.9093 lat=31.1946 depth=0.0 sta=TAS file=TAS nsew=1 usgsformat=0 sacformat=1
rec lon=131.3875 lat=32.8179 depth=0.0 sta=TKD file=TKD nsew=1 usgsformat=0 sacformat=1
rec lon=131.2321 lat=31.8931 depth=0.0 sta=TKO file=TKO nsew=1 usgsformat=0 sacformat=1
rec lon=130.9151 lat=32.6063 depth=0.0 sta=TMC file=TMC nsew=1 usgsformat=0 sacformat=1
rec lon=129.7237 lat=32.8870 depth=0.0 sta=STM file=STM nsew=1 usgsformat=0 sacformat=1
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by eamonustc** [comment] 2017-05-01 13:57
My ifile:
https://www.dropbox.com/sh/u084p1ag0vvqowo/AACyjMGzj4QzX25TnovZy6zMa?dl=0

**Comment by shaharkadmiel** [comment] 2017-05-01 14:13
Everything looks fine to me. It shouldn't matter but I always put the ``material`` lines after the ``ifile`` line.

It might be that your domain is just a little bit bigger than your ifile extents in which case SW4 does not know what properties to prescribe for the extra grid points. The ``block`` command takes care of that by setting a background material for the entire domain. If this is at the edges of your computational grid than don't worry about it.

Disclaimer: I did not try to reproduce your error, I am guessing what the problem is based on my experience with similar issues in the past.

**Comment by eamonustc** [comment] 2017-05-02 01:55
Hi shaharkadmiel:
        Thank you so much! I have checked. My computation domain is smaller than my ifile extents. That's why I confused.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Geographic and Cartesian coordinates of the corners of the computational grid:
0: Lon= 1.294500e+02, Lat=3.090000e+01, x=0.000000e+00, y=0.000000e+00
1: Lon= 1.294500e+02, Lat=3.404410e+01, x=3.500000e+05, y=0.000000e+00
2: Lon= 1.321603e+02, Lat=3.404410e+01, x=3.500000e+05, y=2.500000e+05
3: Lon= 1.320673e+02, Lat=3.090000e+01, x=0.000000e+00, y=2.500000e+05

**** Ifile parameters: *****
filename=kumamoto.dat
CartesianFormat=0
***inside MaterialIfile::extractSurfaceFromGridFile***
Nlon=233 Nlat=403 Nmat=23
Material interface surfaces: lonMin=1.293500e+02, lonMax=1.322500e+02
latMin=3.080000e+01, latMax=3.415000e+01
depthMin=0.000000e+00, depthMax=6.291780e+05
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by andersp** [comment] 2017-05-02 06:12
Your ifile has multiple coinciding surfaces and that triggered a bug when reading the material properties. I have now fixed the problem in the developer branch of our github repository. Please update your source code and recompile.
Thanks,
Anders

**Comment by eamonustc** [comment] 2017-05-04 02:12
Hi andersp:
        Thank you so much for help! I will use the developer branch of SW4.

Best Wishes!

**Closed** 2017-05-04 16:48 UTC
